name: bot
on:
  issue_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, edited, deleted, transferred, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]
  pull_request:
    types: [opened, edited, closed, assigned, unassigned, labeled, unlabeled, reopened, synchronize, ready_for_review, review_requested, review_request_removed]   
    
jobs:
  triage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Che Triage Action
      id: che-triage
      uses: benoitf/che-triage@master
      with:
        read-token: ${{ secrets.GITHUB_TOKEN }}
        write-token: ${{ secrets.GITHUB_TOKEN }}
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
      
